// Epic Games hostnames OG Fortnite builds contact for login, content, matchmaking,
// and XMPP. Chapter 1 mid/late seasons (e.g. 4.5+) use Akamai *.ak.epicgames.com
// shards — those MUST be redirected alongside the older *.ol.epicgames.com hosts.
module.exports = [
  // Akamai CDN shards (Season 4+ and many later builds)
  "account-public-service-prod.ak.epicgames.com",
  "fortnite-public-service-prod.ak.epicgames.com",
  "datarouter-prod.ak.epicgames.com",
  "lightswitch-public-service-prod.ak.epicgames.com",
  "tracking-api-prod.ak.epicgames.com",
  "fortnitecontent-website-prod.ak.epicgames.com",
  // Legacy ol.epicgames.com shards
  "account-public-service-prod.ol.epicgames.com",
  "account-public-service-prod03.ol.epicgames.com",
  "fortnite-public-service-prod11.ol.epicgames.com",
  "fortnite-public-service-prod.ol.epicgames.com",
  "lightswitch-public-service-prod06.ol.epicgames.com",
  "lightswitch-public-service-prod.ol.epicgames.com",
  "datarouter.ol.epicgames.com",
  "xmpp-service-prod.ol.epicgames.com",
  "persona-public-service-prod06.ol.epicgames.com",
  "persona-public-service-prod.ol.epicgames.com",
  "entitlement-public-service-prod08.ol.epicgames.com",
  "entitlement-public-service-prod.ol.epicgames.com",
  "friends-public-service-prod.ol.epicgames.com",
  "friends-public-service-prod06.ol.epicgames.com",
  "catalog-public-service-prod06.ol.epicgames.com",
  "catalog-public-service-prod.ol.epicgames.com",
  "eulatracking-public-service-prod.ak.epicgames.com",
  "eulatracking-public-service-prod.ol.epicgames.com",
  "eulatracking-public-service-prod06.ol.epicgames.com",
  "eulatracking-public-service-prod-m.ol.epicgames.com",
  "affiliate-public-service-prod.ol.epicgames.com",
  "events-public-service-live.ol.epicgames.com",
  "fngw-mcp-gc-livefn.ol.epicgames.com",
  "fngw-svc-gc-livefn.ol.epicgames.com",
  "party-service-prod.ol.epicgames.com",
  "party-service-prod06.ol.epicgames.com",
  "launcher-public-service-prod.ol.epicgames.com",
  "launcher-public-service-prod06.ol.epicgames.com",
  "fortnitecontent-website-prod.ol.epicgames.com",
  "fortnitecontent-website-prod06.ol.epicgames.com",
  "fortnite-public-service-prod03.ol.epicgames.com",
  "fortnite-public-service-prod04.ol.epicgames.com",
  "www.epicgames.com",
  "epicgames.com",
  "account.epicgames.com",
  "api.epicgames.dev",
  "statsproxy-public-service-live.ol.epicgames.com",
  "datastorage-public-service-live.ol.epicgames.com",
  // Caldera (ecosec.on.epicgames.com) must reach REAL Epic on Ch4+ builds.
  // v23+ FortniteLauncher rejects mock HS256 JWTs — it needs Epic's ES256 token.
];
